### PR TITLE
Require an key for OpenAI only when default URL is used

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by jmartisk** [comment]
Does this mean we can now remove the dummy keys from various places in tests and docs samples?

**Comment by jmartisk** [comment]
Probably just tests that use a mock. We don't override the URL in docs samples.

**Comment by geoand** [comment]
Actually I'll leave out fixing the tests for when I get around to https://github.com/quarkiverse/quarkus-langchain4j/issues/446

**Comment by maxandersen** [comment]
Remind me why this is needed ?

Shouldn't we just not do anything for dummy key and have users set that value explicitly ?

**Comment by geoand** [comment]
The point is that the OpenAI extension can be used with other model serving services besided OpenAI and these services may not require an API key

**Pull request merged**
