### PR TITLE
Add minimal html  UI for email me a peom

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #563

So, the pull request adds a minimal index.html that provides a UI for Email me a poem.
It also catches errors and hints users.

Note, the UI is as minimal as it gets (no vaadin components here) for minimalism shake. If we prefer to have a consistent UI all across our samples, I am all for aligning.

**edit**: The PR also improves the prompt, so that the poem is actually displayed in the response.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Makes perfect sense!

**Comment by geoand** [comment]
There seems to be some bug in the UI as I can't see to type anything into it

**Comment by iocanel** [comment]
> There seems to be some bug in the UI as I can't see to type anything into it
Let me check!

**Comment by iocanel** [comment]
> There seems to be some bug in the UI as I can't see to type anything into it

You are not supposed to type anything. It's where the poem is displayed when you click the send me a poem button.

**Comment by iocanel** [comment]
Which seems to be an indication that this is confusing.

**Comment by geoand** [comment]
Ok yeah, in that case it is pretty confusing 😉

**Pull request merged**
