### PR TITLE
Initial implementation of the response augmenter idea

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by cescoffier** [comment]
@geoand This is what I showed you last week.

**Comment by geoand** [comment]
Very cool!

I'll give it a try tomorrow

**Review by geoand — COMMENTED** [review]
Very interesting!

What's left for this to be done?

**Comment by cescoffier** [comment]
Nothing. Let me open it for review.

**Review by geoand — APPROVED** [review]

**Pull request merged**
