### PR TITLE
Introduce the BOM

### PR DESCRIPTION
**Pull request by ppalaga**
~Blocked by https://github.com/quarkiverse/quarkus-langchain4j/pull/251~

### CODE REVIEW

**Comment by ppalaga** [comment]
Could please somebody help me understand what the failing simple-ollama test is supposed to be doing? It has no test classes so the application under test is not even started. Judging on the commit which added it, it is perhaps testing the Ollama dev service? Would a dev mode test not be a better match for that? Doea adding `quarkus-langchain4j-ollama-devservices` as a compile dependency make any sense?

**Comment by ppalaga** [comment]
220d01f: Rebased on top of the latest https://github.com/quarkiverse/quarkus-langchain4j/pull/251

Given that https://github.com/quarkiverse/quarkus-langchain4j/pull/251 is approved, I am marking this one as ready for review.

**Comment by geoand** [comment]
cc @cescoffier

**Comment by ppalaga** [comment]
967bbaf: rebased after #251 was merged

**Pull request closed without merging**
