### PR TITLE
Improve model download progress logging

### PR DESCRIPTION
**Pull request by geoand**
This change includes two things:

* Ration progress log updates
* Include model name in progress log

Originally started because of #1044, but it also handles: #1046 
- Closes: #1044
- Closes: #1046

### CODE REVIEW

**Comment by maxandersen** [comment]
That makes it a bit better - instead of a full screen of progress lines I just get 4 so I get a bit faster stop.

**Comment by geoand** [comment]
I suppose we could make it every second instead of half second.

**Comment by geoand** [comment]
PR updated

**Review by maxandersen — APPROVED** [review]
looks good

**Pull request merged**
