### PR TITLE
Refactor retriever use in `@RegisterAiService`

### PR DESCRIPTION
**Pull request by geoand**
With this change a retriever is no longer
added by default to an AiService,
but needs to be configured explicitly.

- Closes: #184

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
Let's wait after the workshop to merge and release. I will need to update the code of the workshop too.

**Comment by geoand** [comment]
Absolutely!

**Comment by geoand** [comment]
@cescoffier ok to merge now?

**Comment by cescoffier** [comment]
Yes!

**Pull request merged**
