### PR TITLE
Automatically update dependencies for samples during releases

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Nice!

**Comment by geoand** [comment]
This [almost worked](https://github.com/quarkiverse/quarkus-langchain4j/commit/eba307d544eaf41383dcc745cd1f77e5f2e34c3e).

Instead of updating the quarkus langchain4j version it updated the project version itself

**Comment by iocanel** [comment]
I think that the issue is that it uses `-pl` (that works with artifactId) instead of `-f` (that works with path).

**Comment by iocanel** [comment]
Let me try to fix that.

**Pull request merged**
