### PR TITLE
Upgrade to Quarkus Antora - fix issues on Arm Macs

### PR DESCRIPTION
**Pull request by ppalaga**
@cescoffier @maxandersen could you please try whether this solves your problems?

### CODE REVIEW

**Comment by geoand** [comment]
I assume this is superseded by https://github.com/quarkiverse/quarkus-langchain4j/pull/941?

**Comment by ppalaga** [comment]
> I assume this is superseded by https://github.com/quarkiverse/quarkus-langchain4j/pull/941?

Not really, this one contains an important piece of config for the Mac@Arm users.

I have upgraded quarkus-antora to 0.2.0 in this one too, so that #941 can be closed.

**Comment by cescoffier** [comment]
Seems to work - it does not hang forever anymore.

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
Thanks for checking!

**Pull request merged**
