### PR TITLE
Release 0.21.0.CR3

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@gastaldi I want to perform some post release steps so I did https://github.com/quarkiverse/quarkus-langchain4j/blob/main/.github/workflows/release-perform.yml#L22-L43

However I don't see those post release steps having taken place. Any idea what I'm doing wrong?

**Comment by geoand** [comment]
Actually, the whole release probably failed...

**Comment by gastaldi** [comment]
You need to put in a different job, not steps

**Comment by geoand** [comment]
Makes sense. 

That leaves the question of how I can see the action logs when something goes wrong :)

**Comment by gastaldi** [comment]
I see it fails here because the YAML is invalid: https://github.com/quarkiverse/quarkus-langchain4j/actions/runs/11626863204

**Pull request merged**
