### PR TITLE
Add support for structured output in OpenAI

### PR DESCRIPTION
**Pull request by geoand**
- Closes: #1143

### CODE REVIEW

**Comment by geoand** [comment]
@andreadimaio I reused some of your stuff (after realizing that I had redone it...) and that made me wonder whether Watsonx has the same capability as well

**Comment by geoand** [comment]
Thanks for the info!

**Comment by andreadimaio** [comment]
[Here](https://github.com/ollama/ollama/blob/main/docs/api.md#structured-outputs) the Ollama configuration.

**Comment by geoand** [comment]
Cool, let's get this in and you can do a follow up PR if you have time (otherwise I'll look into it soon)

**Pull request merged**
