### PR TITLE
Update to LangChain4j 0.32.0

### PR DESCRIPTION
**Pull request by geoand**
Also includes:

* Use the Quarkus worker pool for in-process embedding models
* Add span for each call to a ChatLanguageModel
* Add metrics for each call to a ChatLanguageModel

- Closes: #700

### CODE REVIEW

**Comment by geoand** [comment]
@jmartisk would you take a look at the Redis failures please?

**Comment by jmartisk** [comment]
Yeah, looking.

**Comment by jmartisk** [comment]
Ok so the problem is this new line:

https://github.com/langchain4j/langchain4j/blob/0.32.0/langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreIT.java#L97

which adds a metadata field or type `UUID`, and I was only expecting numbers and strings when 'guessing' whether the corresponding field in Redis should be type `NUMERIC` or `TEXT`, and my guessing mechanism guesses that this is a number. But when you place a UUID (as a string) into such field and create an embedding for it, Redis won't  return it from the index search operation, because it's invalid (unfortunately, it won't throw any error...).

So I think we can, in this case adjust the guessing mechanism to treat the UUID as a String instead of a Number. 

But, FYI @langchain4j , maybe we should put in place some rules about what values you can put in the metadata. You probably shouldn't be allowed to put any arbitrary objects in there, because it wouldn't be clear how to store them in each underlying embedding store type, and how to perform `equals`, `greaterThan`, etc. operations on it. UUID is probably ok because it can be stored as a string. But I'm thinking maybe we should restrict Metadata values to be String or Number only.

**Comment by jmartisk** [comment]
@langchain4j Ah, sorry I just noticed you already have some checks in place, and explicitly allow UUID along with numbers and strings. That's all good then :)

**Comment by jmartisk** [comment]
Ok great, now we have some failures in Milvus instead

**Comment by geoand** [comment]
lovely...

**Comment by geoand** [comment]
I squashed the the last two (test fix) commits into the first one so we don't have broken intermediate states

**Review by jmartisk — APPROVED** [review]

**Pull request merged**
