### PR TITLE
Add keys to override config for chat, embedding and image-model for Azure OpenAI

### LINKED ISSUE #1154: Azure OpenAI auth - not possible to specify `api-key` for (default)embedding-model
### BUG

when using an embedding model it is possible to specify a dedicated endpoint, but not a dedicated api-key
```
quarkus.langchain4j.azure-openai.embedding-model.resource-name=...
quarkus.langchain4j.azure-openai.embedding-model.api-key=unfortunately-ignored
```

when using ad different `resource-name` as in `quarkus.langchain4j.azure-openai` there will be a different `api-key`  needed as well.  but for `api-key` it falls back to `quarkus.langchain4j.azure-openai` or refusing to start if not present:
```

        SRCFG00014: Exactly of the configuration properties must be present: quarkus.langchain4j.azure-openai.api-key or quarkus.langchain4j.azure-openai.ad-token        
```        
### Expected Behaviour
should be possible to specify
```
quarkus.langchain4j.azure-openai.embedding-model.api-key=...
```

### Workaround
the workaround for some cases might be using a `@ModelName` this works as expected
```
quarkus.langchain4j.azure-openai.<namedembeddingmodel>.resource-name=...
quarkus.langchain4j.azure-openai.<namedembeddingmodel>.api-key=...
```
### Reproduce
<quarkus-langchain4j.version>0.22.0</quarkus-langchain4j.version>
https://github.com/flyinfish/quarkus-langchain4j--samples-azure-openai/tree/use-separate-resource-name/chatbot
https://github.com/flyinfish/quarkus-langchain4j--samples-azure-openai/blob/use-separate-resource-name/chatbot/.env-template

### PR DESCRIPTION
**Pull request by flyinfish**
For chat, embedding, and image-model: api-key, ad-token, api-version

- Closes: #1154

### CODE REVIEW

**Comment by flyinfish** [comment]
@geoand 
that should be pretty much it

i includes ad-token and api-version as they might have the same problem.
with api-version im not to sure, might not help an awful lot

**Comment by geoand** [comment]
Thanks @flyinfish!

@csotiriou WDYT?

**Comment by csotiriou** [comment]
Interesting. From my recollection, having a dedicated `ad-token`s or `api-key`s among dedicated models is something that is new - I don't remember this use case being handled.   

LGTM

**Review by csotiriou — APPROVED** [review]

**Comment by geoand** [comment]
Thanks @csotiriou!

**Pull request merged**
