### PR TITLE
Use Quarkus Antora for testing and live-editting of the docs

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Very interesting, thanks!

**Comment by jmartisk** [comment]
I can't build quarkus-langchain4j anymore after this PR:

```
ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.8.2:build (default) on project quarkus-langchain4j-docs: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkiverse.antora.deployment.AntoraProcessor#buildAntoraSite threw an exception: org.opentest4j.AssertionFailedError: null: Failed to create content cache directory: /antora/docs/target/antora-cache/content; EACCES: permission denied, mkdir '/antora/docs/target/antora-cache' Add the --stacktrace option to see the cause of the error.
```
@ppalaga got any tips what to do? I tried blindly running `mkdir -p docs/antora/docs/target/antora-cache` but that didn't help

**Comment by ppalaga** [comment]
Ouch, sorry about that @jmartisk. Which OS is that? Which line is throwing the error?

**Comment by jmartisk** [comment]
The full error
```
ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.8.2:build (default) on project quarkus-langchain4j-docs: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkiverse.antora.deployment.AntoraProcessor#buildAntoraSite threw an exception: org.opentest4j.AssertionFailedError: null: Failed to create content cache directory: /antora/docs/target/antora-cache/content; EACCES: permission denied, mkdir '/antora/docs/target/antora-cache' Add the --stacktrace option to see the cause of the error.
[ERROR] 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
[ERROR] 	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
[ERROR] 	at io.quarkiverse.antora.deployment.AntoraProcessor$AntoraFrameConsumer.assertNoErrors(AntoraProcessor.java:462)
[ERROR] 	at io.quarkiverse.antora.deployment.AntoraProcessor.buildAntoraSite(AntoraProcessor.java:141)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:842)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```
I'm on Fedora

**Comment by maxandersen** [comment]
I reckon you are running rootful podman or container writing files in group you aren't member of? Shouldn't happen but could explain it. 

What's the owner/group permissions of that directory and contents ?

**Comment by ppalaga** [comment]
> I'm on Fedora

OK, thanks. Then you have some special Podman setup as @maxandersen suggests? 

The extension tries to run Antora container with the UID of the local user - that for sure is what does not work on your machine.

https://github.com/quarkiverse/quarkus-antora/blob/09cf481bfcbfd414ec57f24fcb180b0797d2fe82/deployment/src/main/java/io/quarkiverse/antora/deployment/AntoraProcessor.java#L126

Maybe I need to set the group ID as well?

**Comment by jmartisk** [comment]
I can get it working all the way by removing the explicit setting of the userID (https://github.com/quarkiverse/quarkus-antora/blob/0.0.2/deployment/src/main/java/io/quarkiverse/antora/deployment/AntoraProcessor.java#L126) 

It behaves the same when I run the container manually
```
podman run  -it -v /home/jmartisk/Workspace/quarkus-langchain4j:/antora:Z antora/antora:3.0.1 --cache-dir=./antora-cache docs/antora-playbook.yml
```

this passes, but when I specify the userId of my current user:
```
podman run --user 1000 -it -v /home/jmartisk/Workspace/quarkus-langchain4j:/antora:Z antora/antora:3.0.1 --cache-dir=./antora-cache docs/antora-playbook.yml
```

then I get the same permission error. Which is weird, but I don't understand containers enough to tell what I might have configured wrong

**Comment by jmartisk** [comment]
I'm not aware of anything special, but yeah I can't remember all the stuff that I did with it over the years. It's podman 4.6.2. Running `setenforce 0` didn't help. Doesn't anybody else have this problem? @cescoffier you talked about having some somewhat different problem?

**Comment by maxandersen** [comment]
the issue is volume mounts permission aren't handled consistently between different docker environments.

i don't have a solution except at least for now turn this off and put in profile.

**Comment by maxandersen** [comment]
PR for disabling as it just wont build as is on windows/mac using podman: https://github.com/quarkiverse/quarkus-langchain4j/pull/496

**Pull request merged**
