### PR TITLE
Add bam and watsonx documentation

### PR DESCRIPTION
**Pull request by andreadimaio**
First documentation release for the `bam` and `watsonx` modules.
One note, I added both modules to the `llms.adoc`, but I don't know if it makes sense for the `bam` module.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Very nice, thanks!

**Comment by geoand** [comment]
Seems like there is a conflict now

**Comment by andreadimaio** [comment]
> Seems like there is a conflict now

Yes, I have updated the `pom.xml` file to autogenerate the `quarkus-langchain4j-bam.adoc` and `quarkus-langchain4j-watsonx.adoc`.  Now the conflict should be resolved.

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by andreadimaio** [comment]
Updated `nav.adoc`

**Pull request merged**
