### PR TITLE
Move OpenWebUI Dev UI Actions to deployment classpath

### LINKED ISSUE #854: Is it a good idea to have Testcontainers in the classpath just for Dev UI?
I was developing an application with this extension and when using Jackson, Testcontainers imports kept being in the way because they are shading Jackson.

I was wondering why Testcontainers was around as I was in the runtime classpath and this is because we import `quarkus-devservices-common` in the core for `OpenWebUIJsonRPCService`.

I'm not entirely sure it's a good idea to have Testcontainers around in the runtime. The dev experience is not exactly ideal out of the box when you try to import Jackson classes.
And you end up with quite a bunch of classes you will never use at runtime (except in dev mode).

I'm not exactly sure how we can solve this problem though. Basically, we have:

- Deployment dependencies
- Runtime dependencies
- Dependencies that somehow need to be visible to the runtime but only in dev mode

I'm starting to wonder if we should isolate the Dev UI components in a separate artifact as they are a weird beast.

/cc @aloubyansky @phillip-kruger as it goes beyond Quarkus LangChain4j.

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #854

Ok, so due to the version of quarkus used by langchain, I could not do it as described in https://quarkus.io/guides/dev-ui#jsonrpc-against-the-deployment-classpath as that only became available in https://github.com/quarkusio/quarkus/releases/tag/3.10.0.CR1

So I did it with the DevConsoleManager directly. Not as nice but at least the dependency is not in the deployment classpath. 

I can not test the changes though. Before my changes if I press the start button I get:

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"cause":"unable to replace \"host-gateway\" of host entry \"host.docker.internal:host-gateway\": host containers internal IP address is empty","message":"failed to create new hosts file: unable to replace \"host-gateway\" of host entry \"host.docker.internal:host-gateway\": host containers internal IP address is empty","response":500}

After my changes I still get that. 

Can someone please check these changes ? Maybe @jmartisk  ?

### CODE REVIEW

**Comment by geoand** [comment]
cc @iocanel

**Comment by geoand** [comment]
@jmartisk @iocanel can you please a look at this?

I am having an issue with upgrading to LangChain4j 0.34 and this might help

**Comment by jmartisk** [comment]
The changes are somewhat beyond my understanding, but at least I'll check if I can get it working, hold on

**Comment by jmartisk** [comment]
After clicking the 'Start' button, I get
```
2024-09-06 11:24:15,624 ERROR [io.qua.mut.run.MutinyInfrastructure] (executor-thread-1) Mutiny had to drop the following exception: io.vertx.core.json.EncodeException: Failed to encode as JSON: No serializer found for class java.lang.Object and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.quarkus.devui.runtime.jsonrpc.JsonRpcResponse["result"]->io.quarkus.devui.runtime.jsonrpc.JsonRpcResponse$Result["object"]->com.github.dockerjava.api.command.InspectContainerResponse["Config"]->com.github.dockerjava.api.model.ContainerConfig["ExposedPorts"]->java.util.HashMap["8080/tcp"])
	at io.quarkus.devui.deployment.jsonrpc.DevUIDatabindCodec.toString(DevUIDatabindCodec.java:99)
	at io.quarkus.devui.runtime.jsonrpc.json.JsonMapper$1$1.toString(JsonMapper.java:45)
	at io.quarkus.devui.runtime.jsonrpc.JsonRpcCodec.writeResponse(JsonRpcCodec.java:43)
	at io.quarkus.devui.runtime.jsonrpc.JsonRpcCodec.writeResponse(JsonRpcCodec.java:26)
	at io.quarkus.devui.runtime.comms.JsonRpcRouter.lambda$route$6(JsonRpcRouter.java:215)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:73)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:29)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

(without this PR it works for me)

**Comment by geoand** [comment]
@phillip-kruger ^

**Comment by phillip-kruger** [comment]
I'll have a look soon. Sorry been busy

**Comment by geoand** [comment]
Thanks, no problem!

**Comment by gsmet** [comment]
Won't you move to 3.15 after the 3.15 release? If so maybe this fix can wait until then given apparently there was some infrastructure specifically for these use cases?

**Comment by geoand** [comment]
> Won't you move to 3.15 after the 3.15 release

Yes, that's the plan because if we don't, Quarkus LangChain4j will stop working with `3.16`

**Comment by phillip-kruger** [comment]
@jmartisk or @geoand the original is not working on my laptop. I get the same error for both original and this PR:

```
2024-09-24 16:02:38,713 ERROR [io.qua.dev.run.jso.JsonRpcCodec] (executor-thread-4) Error in JsonRPC Call: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"cause":"unable to replace \"host-gateway\" of host entry \"host.docker.internal:host-gateway\": host containers internal IP address is empty","message":"failed to create new hosts file: unable to replace \"host-gateway\" of host entry \"host.docker.internal:host-gateway\": host containers internal IP address is empty","response":500}

        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
        at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:42)
        at io.quarkiverse.langchain4j.runtime.devui.OpenWebUIJsonRPCService.startOpenWebUI(OpenWebUIJsonRPCService.java:127)
        at io.quarkiverse.langchain4j.runtime.devui.OpenWebUIJsonRPCService_Subclass.startOpenWebUI$$superforward(Unknown Source)
        at io.quarkiverse.langchain4j.runtime.devui.OpenWebUIJsonRPCService_Subclass$$function$$3.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
        at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
        at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at io.quarkiverse.langchain4j.runtime.devui.OpenWebUIJsonRPCService_Subclass.startOpenWebUI(Unknown Source)
        at io.quarkiverse.langchain4j.runtime.devui.OpenWebUIJsonRPCService_ClientProxy.startOpenWebUI(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.devui.runtime.comms.JsonRpcRouter.lambda$invoke$0(JsonRpcRouter.java:108)
        at io.smallrye.mutiny.unchecked.UncheckedSupplier.lambda$toSupplier$0(UncheckedSupplier.java:41)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

I am using podman. Can we work together to get this in, as I am not getting anywhere. Let me know

**Comment by jmartisk** [comment]
@phillip-kruger Please run the formatter.
It now works (at least on my machine :) )

**Comment by geoand** [comment]
Unfortunately this need a rebase

**Comment by phillip-kruger** [comment]
@geoand rebase done

**Comment by geoand** [comment]
Thanks!

@jmartisk can you check please?

**Comment by jmartisk** [comment]
I'll have a look asap (unfortunately tasks are piling up...)

**Comment by geoand** [comment]
🙏🏽

**Review by jmartisk — APPROVED** [review]

**Comment by jmartisk** [comment]
Works for me! (Hopefully not just me......)

**Pull request merged**
