### PR TITLE
Introduce a way to configure tools per method of an AiService

### PR DESCRIPTION
**Pull request by geoand**
This is done using the new `@ToolBox` annotation

- Closes: #42

### CODE REVIEW

**Comment by geoand** [comment]
@cescoffier can you give this a try with the example you had in mind for the `@ToolBox` use case?

**Comment by cescoffier** [comment]
@geoand I will try it tomorrow.

**Comment by geoand** [comment]
🙏

**Comment by geoand** [comment]
I'll fix the conflict if we decide we want this

**Comment by geoand** [comment]
@cescoffier can you have a look at this one?

**Comment by cescoffier** [comment]
@geoand Yes, I will try to use it on the demo we did last week.

**Comment by geoand** [comment]
🙏🏼

**Comment by cescoffier** [comment]
Works! 

```java

    @UserMessage("""
            Extract the policy number from the given claim.
            Only return the policy number.
            
            {text}
            """)
    String extractPolicyNumber(String text);

    @UserMessage("""
            Check if there is an existing claim related to the given claim.
            Return the claim id, null if none.
                        
            The existing claim can be found by identifying the policy number from the given claim.
            
            If no claim is found, return -1.
            
            {text}
            
             """)
    @ToolBox(ClaimService.class)
    Long findRelatedClaims(String text);
```

**Comment by geoand** [comment]
Thanks for checking!

I will check it

**Comment by geoand** [comment]
Done

**Pull request merged**
