### PR TITLE
Introduce quarkus-langchain4j-bom

### PR DESCRIPTION
**Pull request by gastaldi**
- Closes https://github.com/quarkiverse/quarkus-langchain4j/pull/252
- Closes https://github.com/quarkiverse/quarkus-langchain4j/pull/215

Unlike the other PRs, this doesn't require any maintenance when introducing a new module. 
For reference, this plugin is also used in https://github.com/smallrye/smallrye-common/blob/main/pom.xml#L203 and https://github.com/smallrye/smallrye-reactive-messaging/blob/main/pom.xml#L609

### CODE REVIEW

**Comment by geoand** [comment]
cc @ppalaga

**Comment by ppalaga** [comment]
The approach not to have a dedicated BOM module looks interesting. In that way, the POM is not a part of Maven reactor and can thus be generated before it is read from modules using it. I like it very much.

The BOM as installed by the current PR contains just io.quarkiverse.langchain4j extensions. I think we should also include some important transitives, such as langchain4j or Apache POI.

**Comment by geoand** [comment]
> such as langchain4j or Apache POI

Yeah, that would be very nice

**Comment by gastaldi** [comment]
> I think we should also include some important transitives, such as langchain4j or Apache POI.

I am not sure about that. Transitives (as the name implies) are indirectly resolved from the dependencies that are declared in the BOM, so I don't think it would make sense to include them.

**Comment by geoand** [comment]
The Langchain4j dependency is definitely needed as very often users will need to mix dependencies from that project

**Comment by gsmet** [comment]
> The BOM as installed by the current PR contains just io.quarkiverse.langchain4j extensions. I think we should also include some important transitives, such as langchain4j or Apache POI.

Actually, no, it shouldn't. The BOM of a project is supposed to only enforce the artifact it publishes.
Otherwise things quickly become a nightmare with all the BOMs trying to enforce various things.

In Quarkus, we fought hard to avoid this.

Now for LangChain4j itself, I must admit I'm torn because it seems like a good idea to enforce it.

/cc @aloubyansky

**Comment by aloubyansky** [comment]
> > The BOM as installed by the current PR contains just io.quarkiverse.langchain4j extensions. I think we should also include some important transitives, such as langchain4j or Apache POI.
> 
> Actually, no, it shouldn't. The BOM of a project is supposed to only enforce the artifact it publishes. Otherwise things quickly become a nightmare with all the BOMs trying to enforce various things.
> 
> In Quarkus, we fought hard to avoid this.

It's not completely avoidable though.

> Now for LangChain4j itself, I must admit I'm torn because it seems like a good idea to enforce it.

Makes perfect sense to me.

**Comment by maxandersen** [comment]
Why is this bom to be used for ?

Users of Langchain4j extension? We don't have such support in code quarkus and cli yet hence why im asking.

**Comment by ppalaga** [comment]
> Why is this bom to be used for ?
> 
> Users of Langchain4j extension? 

That and Camel Quarkus once we integrate Langchain4j to Camel. 

> We don't have such support in code quarkus and cli yet hence why im asking.

Langchain4j could join the platform at some point.

**Comment by geoand** [comment]
> > Now for LangChain4j itself, I must admit I'm torn because it seems like a good idea to enforce it.
> 
> Consumers of this BOM will (at least) depend on the `quarkus-langchain4j-core` which resolves to the correct langchain4j version, no? 

The issue arises when users want to use something else from upstream Langchain4j that is not a transitive dependency of the extension.
In that case they don't know which version to use

**Comment by maxandersen** [comment]
> > Why is this bom to be used for ?
> 
> > 
> 
> > Users of Langchain4j extension? 
> 
> 
> 
> That and Camel Quarkus once we integrate Langchain4j to Camel. 

Yes so we have a problem if we bunch everything camel depends on in - we really need to allow for extensions not in platform to offer/suggest bom to be added when users add their extension so users can use this even when frequently updated. 
> 
> 
> > We don't have such support in code quarkus and cli yet hence why im asking.
> 
> 
> 
> Langchain4j could join the platform at some point.

The longer we can avoid that though...it's a very high frequent updating library set at this stage.

**Comment by maxandersen** [comment]
Automation doesn't fix breakages it introduces :)

**Comment by geoand** [comment]
Right, at this point it's too early to have any of the Langchain4j stuff be in the platform.
Maybe towards the end of the year...

**Comment by ppalaga** [comment]
Thanks for importing langchain4j-bom. 

I wonder whether the plugin can be configured to add some exclusions to an entry?

`langchain4j-milvus` brings some clutter [banned by Quarkus](https://github.com/quarkusio/quarkus/blob/main/independent-projects/enforcer-rules/src/main/resources/enforcer-rules/quarkus-banned-dependencies.xml), such as `com.google.android:annotations`, `org.apache.logging.log4j:log4j-slf4j-impl`, `org.checkerframework:checker-qual` and `org.codehaus.mojo:animal-sniffer-annotations`

**Comment by gastaldi** [comment]
@ppalaga best I can do is to declare an exclusion before the BOM. 
Perhaps a better idea is to have a new BOM in the project as a new project excluding the banned dependencies and import that instead of the official langchain4j BOM?

**Comment by ppalaga** [comment]
> @ppalaga best I can do is to declare an exclusion before the BOM (see [69bea4a](https://github.com/quarkiverse/quarkus-langchain4j/commit/69bea4ab1e82000551fbcd6f3d133b928725d83e)). 

That should work. 
I assume the plugin cannot flatten, right?

> Perhaps a better idea is to have a new BOM in the project as a new module excluding the banned dependencies and import that instead of the official langchain4j BOM?

What would be the benefit compared to 69bea4a?

**Comment by gastaldi** [comment]
@ppalaga 

> What would be the benefit compared to [69bea4a](https://github.com/quarkiverse/quarkus-langchain4j/commit/69bea4ab1e82000551fbcd6f3d133b928725d83e)?

You'd have a single place to list the langchain4j artifacts and their exclusions, which could be reused inside this project too

**Comment by ppalaga** [comment]
Anyway, this PR is good enough to get merged from my PoV.

**Comment by gastaldi** [comment]
> Sorry, not sure I follow. The config of the plugin is also a single place, no? By importing the generated BOM in the top pom.xml, you actually reuse what you defined in the plugin config for the modules of this project. Or you mean something else?
 
Of course, that works too, it's just that you don't have the IDE auto-completion and all the IDE goodies in this case 😉

**Comment by gastaldi** [comment]
BTW I created https://github.com/langchain4j/langchain4j-embeddings/pull/10 which creates a BOM for the langchain4j-embeddings project

**Comment by geoand** [comment]
Mind posting what the generate BOM looks like?

**Comment by ppalaga** [comment]
As of 16c30c0, this BOM is generated:
```
<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.quarkiverse.langchain4j</groupId>
    <artifactId>quarkus-langchain4j-bom</artifactId>
    <version>999-SNAPSHOT</version>
    <name>Quarkus LangChain4j : BOM</name>
    <packaging>pom</packaging>
    <description>Centralized dependencyManagement for the Quarkus LangChain4j Project</description>
    
    <url>https://quarkiverse.io</url>    
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    
    
    <scm>
        <connection>scm:git:git@github.com:quarkiverse/quarkus-langchain4j.git</connection>
        <developerConnection>scm:git:git@github.com:quarkiverse/quarkus-langchain4j.git</developerConnection>
        <url>https://github.com/quarkiverse/quarkus-langchain4j</url>
        <tag>HEAD</tag>
    </scm>
        
    <distributionManagement>
      
      <repository>
        <id>oss.sonatype</id>
        <name>${model.distributionManagement.repository.name}</name>
        <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        <layout>default</layout>
      </repository>
            
      <snapshotRepository>
        <id>ossrh</id>
        <name>${model.distributionManagement.snapshotRepository.name}</name>
        <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
        <layout>default</layout>
      </snapshotRepository>
      
    </distributionManagement>
        
    <developers>
        <developer>
            <id>quarkus</id>
            <name>Quarkus Community</name>
        </developer>
    </developers>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-core</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-core-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-chroma</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-chroma-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-openai-common</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-openai</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-hugging-face</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-redis</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-pinecone</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-openai-common-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-openai-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-redis-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-pinecone-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-pgvector</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-pgvector-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-hugging-face-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-bam</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-bam-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-watsonx</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-watsonx-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-milvus</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-milvus-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-ollama</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-ollama-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-ollama-devservices</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-azure-openai</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-azure-openai-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-openshift-ai</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.langchain4j</groupId>
                <artifactId>quarkus-langchain4j-openshift-ai-deployment</artifactId>
                <version>999-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-milvus</artifactId>
                <version>0.25.0</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.google.android</groupId>
                        <artifactId>annotations</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-slf4j-impl</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.checkerframework</groupId>
                        <artifactId>checker-qual</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>animal-sniffer-annotations</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bom</artifactId>
                <version>0.25.0</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
```

**Comment by geoand** [comment]
Looks nice to me, +1.

I would like to hear from others as well though

**Comment by ppalaga** [comment]
Could we please merge to be able to move on?

**Comment by geoand** [comment]
cc @cescoffier @gsmet

**Comment by gsmet** [comment]
I’m on PTO but from what I can see it looks like a good compromise. 

What would be awesome is to have something in Quarkus which automatically contributes the BOM when we add one of the extensions.

**Comment by geoand** [comment]
> What would be awesome is to have something in Quarkus which automatically contributes the BOM when we add one of the extensions.

Yeah, that part of the tooling would be awesome

**Pull request merged**
