### PR TITLE
Show how OIDC ModelAuthProvider can be used with Azure OpenAI

### PR DESCRIPTION
**Pull request by sberyozkin**
Replaces #634.

This PR aims to show how to use multiple model providers (Vertex AI Gemini, Azure OpenAI) and how they can access models using OIDC access tokens authorized by users authenticated to Quarkus with either Google or Microsoft Entra ID.

I've confirmed the updated demo still works for Vertex AI Gemini but unfortunately I did not have time yet and a bit vague about how to setup my Azure tenant correctly, the earlier tries with #634 did not succeed. I'll look into it a bit later and might ask the community for some help, and once it is confirmed, by myself or someone else independently, the PR should be ready to go...

### CODE REVIEW

**Comment by sberyozkin** [comment]
I'll try to get back to it after PTO and resolve conflicts as well

**Comment by geoand** [comment]
🙏🏼

**Comment by geoand** [comment]
This will need to be rebased when it's picked up again

**Comment by sberyozkin** [comment]
@geoand I've made it working for Azure OpenAI and the user authentication token, it will be quite nice once a few things are cleaned up and we can show both Gemini and Azure Open AI without configuring shared API keys, I had to do some workaround though related to ModelProvider resolution, I'll open another issue to discuss

**Comment by sberyozkin** [comment]
Something did not workout with the rebase, somehow I picked up the pgvector related code here, but I'll recreate a PR later, not  a problem

**Comment by geoand** [comment]
Thanks @sberyozkin

**Comment by sberyozkin** [comment]
Closing it, will open a new one soon

**Pull request closed without merging**
