### PR TITLE
Use custom integration with Jlama

### PR DESCRIPTION
**Pull request by geoand**
This will allow us to move quicker WRT Jlama

### CODE REVIEW

**Comment by geoand** [comment]
cc @mariofusco

**Review by mariofusco — APPROVED** [review]

**Comment by geoand** [comment]
One this is in, we can go to work on Jlama :)

**Comment by geoand** [comment]
Give me some CI where I can run them and I'll gladly add them

**Comment by edeandrea** [comment]
Just giving you a hard time :D

**Comment by geoand** [comment]
😆

**Pull request merged**
