### PR TITLE
Update watsonx module: Add Text Extraction APIs, Configuration changes, and Pretty-Print logging

### PR DESCRIPTION
**Pull request by andreadimaio**
- **Add TextExtraction APIs:** APIs to perform OCR on documents. For now, the use of these APIs is enabled by casting the `ChatLanguageModel`;
- **Remove PromptFormatter classes:** With the introduction of the `/chat` API, the `PromptFormater` classes are no longer needed;
- **Create two different configurations ChatModelConfig and GenerationModelConfig:** Created separate `ChatModelConfig` and `GenerationModelConfig` classes for easier  configuration;
- **Add space-id parameter**;
- **Add model list link to ScoringModel documentation**;
- **Add tool_choice parameter and rename TextChatParameterTools to TextChatParameterTool**;
- **Response logging with pretty-printing**;

Tell me if I have to do a squash after the review.

### CODE REVIEW

**Comment by andreadimaio** [comment]
One note, I don't see any changes in the `quarkus-langchain4j-watsonx.adoc` in my workspace (the file with all the attributes). Is this something that only updates when the github pipeline is run?

**Comment by geoand** [comment]
Can you try running `mvn clean install -DskipTests` on the whole project?

It should update the docs

**Comment by geoand** [comment]
Not sure what the issue is to be honest

**Review by geoand — APPROVED** [review]

**Comment by andreadimaio** [comment]
> Not sure what the issue is to be honest

Let's wait for a new release, if the attributes are still not updated then I'll open an issue.

**Comment by geoand** [comment]
👍🏽

**Pull request merged**
