### PR TITLE
Convert retirement-money-market.png to jpg

### PR DESCRIPTION
**Pull request by jmartisk**
To be sure, @geoand could you try and check that it fixes it for you?

Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/418

### CODE REVIEW

**Comment by geoand** [comment]
Same problem for me unfortunately

**Comment by jmartisk** [comment]
Uhm, great, and it started working with png for me again.

**Comment by jmartisk** [comment]
Then let's try and just get rid of pictures, if that helps, PDF and ODT should be enough to demonstrate the capabilities...

**Comment by jmartisk** [comment]
But generally I think langchain4j (and by extension, Quarkus), should offer some options to configure Tika (disable/enable OCR), which I don't think is possible right now.

**Comment by geoand** [comment]
> But generally I think langchain4j (and by extension, Quarkus), should offer some options to configure Tika (disable/enable OCR), which I don't think is possible right now.

cc @langchain4j

**Review by geoand — APPROVED** [review]

**Comment by langchain4j** [comment]
Tika loader can be configured: https://github.com/langchain4j/langchain4j/blob/6fd8fbcade91f9726489a6e40328cecc3b9ef660/document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java#L49

**Comment by jmartisk** [comment]
Aha ok, that will need some thinking on our side, whether we want to generally add configuration properties for different types of document parser (and manage the parsers in CDI), or just something simple in the easy rag extension specifically for Tika (and assume that in other cases, it will be up to the user to build an appropriate document parser)

**Pull request merged**
