### PR TITLE
Fix registration of embedding model for Easy RAG

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/1129

### CODE REVIEW

**Comment by jmartisk** [comment]
@manovotn may want to have a look too, as it is related to something that started failing after https://github.com/quarkiverse/quarkus-langchain4j/commit/b1c52cbbb667ed86fc31c7478c53015d6fd99b6f

This tries to avoid a duplicate `SelectedEmbeddingModelCandidateBuildItem` when Easy RAG is present and the user has chosen an explicit provider for the embedding model

**Comment by edeandrea** [comment]
I'm building this locally now

**Review by edeandrea — APPROVED** [review]
I can confirm this indeed fixes #1129.

**Review by geoand — APPROVED** [review]

**Review by manovotn — APPROVED** [review]
> @manovotn may want to have a look too, as it is related to something that started failing after https://github.com/quarkiverse/quarkus-langchain4j/commit/b1c52cbbb667ed86fc31c7478c53015d6fd99b6f

Right, I see the bit that I missed there :+1:

**Pull request merged**
