### PR TITLE
Revert poem sample's dependency

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by geoand — CHANGES_REQUESTED** [review]
A release is under way, so it should get updated

**Comment by jmartisk** [comment]
Ok let's wait and then close this PR if it works

**Comment by geoand** [comment]
Of course it failed...

**Comment by geoand** [comment]
Anyway, I have to update main to fix the release, so I'll fix this as well.

In any case thanks  for spotting this!

**Comment by jmartisk** [comment]
Ok :)

**Pull request closed without merging**
