### PR TITLE
Updates to avoid code duplication

### PR DESCRIPTION
**Pull request by karesti**
This Pr is related to this one 

https://github.com/langchain4j/langchain4j/pull/845

### CODE REVIEW

**Comment by karesti** [comment]
I created a PR in langchain4j to avoid duplication of code

What do you think about this ?

**Comment by geoand** [comment]
You're in charge of the Infinispan stuff, so whatever you think is best :)

**Comment by karesti** [comment]
@geoand I was also thinking overall strategy concerning other integrations, since the code is duplicated and the effort seems high

**Comment by geoand** [comment]
Sure, but we'll see tackle it on a per case badis

**Pull request closed without merging**
