### PR TITLE
Pass configs and an extension value to make sure vector extensions are created and can be overridden by passing that config

### PR DESCRIPTION
**Pull request by shrikanthkr**
Fixes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1139

### CODE REVIEW

**Review by jmartisk — APPROVED** [review]
Nice! Thanks!

**Comment by shrikanthkr** [comment]
Sorry. Will get that done

**Comment by shrikanthkr** [comment]
@jmartisk formatting is done. Would there be anything else required on the PR?

**Comment by jmartisk** [comment]
It's still complaining about unsorted imports

**Comment by shrikanthkr** [comment]
@jmartisk I ran `./mvnw -B clean install -DskipTests -Dno-format -ntp`  command to verify .
and for fixing imports `./mvnw impsort:sort -Dimpsort.sourcefile=/Users/shrikanth/Shrikanth/shrikanth-quarkus-langchain4j/embedding-stores/pgvector/runtime/src/main/java/io/quarkiverse/langchain4j/pgvector/PgVectorAgroalPoolInterceptor.java`.

I hope this would fix it.

**Pull request merged**
