### PR TITLE
Introduce global logging properties

### PR DESCRIPTION
**Pull request by geoand**
This allows us to use quarkus.langchain4j.log-requests=true instead of specifying needing to specify the provider as well

### CODE REVIEW

**Comment by jmartisk** [comment]
Great idea!
There's a failure in a watsonx test that seems related

**Comment by geoand** [comment]
Right, I'll fix it soon

**Comment by jmartisk** [comment]
I think it would also be nice to mention it on the Getting started page in the docs

**Comment by geoand** [comment]
Having it in the docs definitely makes sense, but I am not sure which page you are referring to.

**Comment by jmartisk** [comment]
the landing page https://docs.quarkiverse.io/quarkus-langchain4j/dev/index.html :)

**Comment by geoand** [comment]
Would you like to push a commit with that change?

**Comment by jmartisk** [comment]
Sure

**Comment by geoand** [comment]
🙏🏼

**Review by cescoffier — APPROVED** [review]

**Comment by maxandersen** [comment]
Bedt feature ever ! (At least this morning thus far).

**Review by jmartisk — APPROVED** [review]

**Pull request merged**
