### PR TITLE
Make use of new stuff in the Redis DataSource API

### PR DESCRIPTION
**Pull request by jmartisk**
Needs Quarkus 3.6.0

### CODE REVIEW

**Comment by geoand** [comment]
I assume we can use `3.6.0.CR1` for this, right?

**Comment by jmartisk** [comment]
I guess so! I've added the upgrade to this PR, let's see

**Review by geoand — COMMENTED** [review]
LGTM, but I'd like @cescoffier to weigh in

**Comment by geoand** [comment]
I rebased this onto `main` in order to make sure everything still works with the latest changes I made there.

**Comment by jmartisk** [comment]
I've updated Quarkus from `3.6.0.CR1` to `3.6.0` now.

**Comment by geoand** [comment]
@cescoffier can you please review?

**Review by cescoffier — APPROVED** [review]
Awesome!

**Pull request merged**
