### PR TITLE
Image model Dev UI page + docs

### LINKED ISSUE #202: Dev UI page for experimenting with image models

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #202

### CODE REVIEW

**Comment by jmartisk** [comment]
And yea it seems that some changes in generated docs snuck in, perhaps with some previous PR it got forgotten to add that?

**Review by geoand — APPROVED** [review]
This is awesome, thanks!

**Comment by geoand** [comment]
@jmartisk if you don't have any more upcoming changes, I would like to cut a `0.6.0` release to include this.

**Comment by jmartisk** [comment]
Sure!

**Pull request merged**
