### PR TITLE
Moving samples updates to release-prepare.yml

### PR DESCRIPTION
**Pull request by gastaldi**
Also copying the contents until we introduce a hook

### CODE REVIEW

**Comment by gastaldi** [comment]
@geoand this should give you a smoother release process

**Comment by geoand** [comment]
What does this do exactly?

I have a release in progress and what to understand if I should cancel it or not

**Comment by gastaldi** [comment]
Basically does the samples updates in the `release-prepare.yml`, before `mvn release:prepare` is called

**Comment by geoand** [comment]
But that means that the samples are updated before the release is done, no?
So if a release goes bad, then the samples will contain an erroneous version, right?

**Comment by gastaldi** [comment]
This ensures that the same version is used in the tagged version. If a release goes bad, nothing is pushed, so nothing changes

**Comment by gastaldi** [comment]
Let me know when you release again, I'd like to see the execution logs

**Comment by geoand** [comment]
Sure thing

**Comment by gastaldi** [comment]
- https://github.com/quarkiverse/.github/pull/8 introduces support for pre- and post- hooks with bash scripts

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
So I assume now this can be rewritten to use the hooks?

**Comment by gastaldi** [comment]
> So I assume now this can be rewritten to use the hooks?

Yes, I'll change it once I test and merge the hooks PR

**Comment by geoand** [comment]
👍🏽

**Comment by gastaldi** [comment]
@geoand tested and updated!

**Review by geoand — APPROVED** [review]
Thanks a lot!

**Comment by gastaldi** [comment]
@geoand I noticed your custom code is failing while releasing: https://github.com/quarkiverse/quarkus-langchain4j/actions/runs/11628913393/job/32384921060

**Comment by gastaldi** [comment]
But probably whis PR will fix it, we'll see

**Comment by geoand** [comment]
Yeah, that's why I didn't put any more effort into it :)

**Pull request merged**
