### PR TITLE
Ability to disable integrations

### LINKED ISSUE #130: Ability to serve a default response?
Since integrating with OpenAI costs real money, should there be a way that I can serve a default response if I want to "turn off" the integration at runtime? Maybe when I'm running in dev mode or if I'm doing a quick demo I don't want it to make "real" calls to an openai provider.

### PR DESCRIPTION
**Pull request by edeandrea**
This provides configuration around langchain4j/langchain4j#549 which will create disabled versions of the models based on configuration.

- Closes: #130

### CODE REVIEW

**Comment by geoand** [comment]
This will need a rebase and revert of the docs changes as they have been updated by another PR

**Comment by edeandrea** [comment]
Should the docs not get updated at all? Or just re-updated via `mvn install` after a rebase?

**Comment by geoand** [comment]
This time they should not get updated as I already updated them

**Comment by edeandrea** [comment]
@geoand I've rebased. This should be good to go once the checks run.

**Comment by geoand** [comment]
How about some docs on why/when to use it?

**Comment by edeandrea** [comment]
> How about some docs on why/when to use it?

Since this is cross-cutting across all the modules, where do you think the best place for that kind of doc is? Something new under advanced topics?

**Comment by geoand** [comment]
> Something new under advanced topics?

Sounds good

**Comment by edeandrea** [comment]
I've added some documentation. Let me know what you think.

**Review by geoand — APPROVED** [review]
Lovely!

**Pull request merged**
