### PR TITLE
Enable observability by default in the email-me-a-poem sample

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@jmartisk WDYT?

**Comment by maxandersen** [comment]
didn't we add that flag to avoid the sample to be slow to start (fetching LGTM containers is not small + not all have container env) + lgtm haven't yet started smoothly for me on podman (going to try that now to see if improved)

**Comment by maxandersen** [comment]
```
2024-08-08 16:25:26,656 INFO  [io.qua.obs.dev.DevResources] (build-13) Activating dev resources
2024-08-08 16:25:26,657 INFO  [io.qua.obs.dev.DevResources] (build-13) Found dev resources: [io.quarkus.observability.devresource.lgtm.LgtmResource@482f1fc6]
2024-08-08 16:25:28,792 INFO  [io.qua.mai.dep.MailpitProcessor] (build-59) Dev Services for Mailpit started.
2024-08-08 16:25:28,870 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  2 pending,  1 downloaded,  0 extracted, (0 bytes/? MB)
2024-08-08 16:25:34,554 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending,  2 downloaded,  0 extracted, (51 MB/? MB)
2024-08-08 16:25:39,661 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending,  3 downloaded,  0 extracted, (92 MB/? MB)
2024-08-08 16:25:40,415 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending,  4 downloaded,  0 extracted, (96 MB/? MB)
2024-08-08 16:25:40,830 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending,  5 downloaded,  0 extracted, (96 MB/? MB)
2024-08-08 16:25:41,189 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending,  6 downloaded,  0 extracted, (99 MB/? MB)
2024-08-08 16:25:41,612 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending,  7 downloaded,  0 extracted, (100 MB/? MB)
2024-08-08 16:25:42,503 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending,  8 downloaded,  0 extracted, (105 MB/? MB)
2024-08-08 16:25:42,897 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending,  9 downloaded,  0 extracted, (105 MB/? MB)
2024-08-08 16:25:43,257 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending, 10 downloaded,  0 extracted, (109 MB/? MB)
2024-08-08 16:25:43,643 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending, 11 downloaded,  0 extracted, (109 MB/? MB)
2024-08-08 16:25:43,962 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending, 12 downloaded,  0 extracted, (109 MB/? MB)
2024-08-08 16:25:44,309 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending, 13 downloaded,  0 extracted, (113 MB/? MB)
2024-08-08 16:25:44,665 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending, 14 downloaded,  0 extracted, (113 MB/? MB)
2024-08-08 16:25:45,073 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending, 15 downloaded,  0 extracted, (115 MB/? MB)
2024-08-08 16:25:45,438 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending, 16 downloaded,  0 extracted, (117 MB/? MB)
2024-08-08 16:25:45,907 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending, 17 downloaded,  0 extracted, (118 MB/? MB)
2024-08-08 16:25:46,279 INFO  [tc.doc.io/.4.0] (docker-java-stream-1107689161) Pulling image layers:  5 pending, 18 downloaded,  0 extracted, (121 MB/? MB)

--
Lgtm Dev Services Starting: 2024-08-08 16:25:26,774 INFO  [org.tes.uti.RegistryAuthLocator] (build-13) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: docker.io/grafana/otel-lgtm:latest, configFile: /Users/manderse/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Could not execute [docker-credential-desktop, get]. Error=2, No such file or directory
```

its been sitting stuck there for 30+ seconds...

**Comment by maxandersen** [comment]
fyi, it completed in ~5 minutes and then yelled at me for not having set the openai key :)

**Comment by geoand** [comment]
Ouch....

**Pull request closed without merging**
