### PR TITLE
Add domain config for Azure AI

### PR DESCRIPTION
**Pull request by duchamk**
- Resolves: #660

### CODE REVIEW

**Comment by geoand** [comment]
Thanks a lot!

@csotiriou do you want to review?

**Review by csotiriou — APPROVED** [review]

**Comment by csotiriou** [comment]
@geoand @duchamk I approved this by mistake, sorry about that. I did find an issue. 

Since this property is overridable, it should follow the same pattern as with `endPointFor()`, `resourceNameFor()`, and the `@WithDefault` would should only apply to the parent property, not the one that overrides the parent property. 

Can we change that?

**Comment by geoand** [comment]
No problem!

Feel free to do a follow-upi

**Comment by geoand** [comment]
@csotiriou ^

**Pull request merged**
