### PR TITLE
Fix issue with Azure OpenAI and metrics usage

### PR DESCRIPTION
**Pull request by geoand**
Essentially the ChatLanguageModel was being
built too early thus messing up the construction
order of the dependencies

- Fixes: #731

### CODE REVIEW

**Comment by geoand** [comment]
This fails because of the use cce63037 - I'll first need to fix that

**Comment by andreadimaio** [comment]
I moved the `builder.build()` outside of the `Supplier<>` to have the same instance for the ChatLanguageModel and the TokenCountEstimator. Is this also done for the `watsonx` and `bam` modules.

**Comment by andreadimaio** [comment]
And also remove the following lines from the [MultipleTokenCountEstimatorProvidersTest](https://github.com/quarkiverse/quarkus-langchain4j/blob/main/integration-tests/multiple-providers/src/test/java/org/acme/example/multiple/MultipleTokenCountEstimatorProvidersTest.java) class: `#50`, `#57`, `#64`

**Comment by geoand** [comment]
Yup, I'm going to revert those changes

**Comment by geoand** [comment]
I tried a few things, but in the end the obvious fix is the one that makes most sense

**Pull request merged**
